import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./(shared)/Navbar";

// Fuentes locales
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Este es el layout principal de la aplicación
export default function Layout({ children }) {
  return (
    // Agregar la etiqueta <html> y <body> para envolver toda la aplicación
    <html lang="en">
      <body>
        {/* Espacio para el contenido debajo de la Navbar */}
        <main className="w-full min-h-screen bg-slate-50"> {/* Añadimos más espacio para la navbar */}
          {children}
        </main>
        <Navbar/>
        {/* Barra de navegación siempre visible en la parte inferior */}
      </body>
    </html>
  );
}
